In [1]:
import pandas as pd
import random
import os
import dill

In [2]:
data_path = "./processed_data/pretrain_lab_data.pkl"
data_df = pd.read_pickle(data_path)

In [3]:
def add_name(row):
    typ = row["TYPE"]
    if typ == "MED":
        item_id = row["NDC"]
    elif typ in ["DIAG", "PROC"]:
        item_id = row["ICD9_CODE"]
    elif typ == "LAB":
        item_id = row["ITEMID"]
    idx = vocab.get_word_id(item_id, typ)
    row["NAME"] = vocab.idx2detail[idx]
    return row

In [4]:
# data_dir = "/home/xyz/xyz/Datasets/mimiciii-1.4/"
# diag_df = pd.read_csv(os.path.join(data_dir, "D_ICD_DIAGNOSES.csv"))
# proc_df = pd.read_csv(os.path.join(data_dir, "D_ICD_PROCEDURES.csv"))
# labitem_df = pd.read_csv(os.path.join(data_dir, "D_LABITEMS.csv"))
vocab = dill.load(open("./processed_data/pretrain_lab_vocab.pkl", "rb"))

In [5]:
# subject_id = data_df["SUBJECT_ID"][random.randint(0, len(data_df))]
# data_df = data_df[data_df["SUBJECT_ID"] == subject_id]

In [6]:
hadm_id = 149672
data_df = data_df[data_df["HADM_ID"] == hadm_id]
data_df.iloc[2580:2620,:].apply(add_name, axis=1)
# data_df = data_df.apply(add_name, axis=1)
# data_df

,SUBJECT_ID,HADM_ID,DATETIME,NDC,TYPE,ICD9_CODE,ITEMID,VALUENUM,VALUEUOM,FLAG,NAME
855993,1780,149672,2140-07-10 15:00:00,NaN,LAB,NaN,50970.0,3.60,MG/DL,normal,Phosphate
855994,1780,149672,2140-07-10 15:00:00,NaN,LAB,NaN,50971.0,4.70,MEQ/L,normal,Potassium
855995,1780,149672,2140-07-10 15:00:00,NaN,LAB,NaN,50983.0,135.00,MEQ/L,normal,Sodium
855996,1780,149672,2140-07-10 15:00:00,NaN,LAB,NaN,51006.0,39.00,MG/DL,abnormal,Urea Nitrogen
855997,1780,149672,2140-07-10 15:05:00,NaN,LAB,NaN,51237.0,2.80,,abnormal,INR(PT)
855998,1780,149672,2140-07-10 15:05:00,NaN,LAB,NaN,51274.0,26.90,SEC,abnormal,PT
855999,1780,149672,2140-07-10 15:05:00,NaN,LAB,NaN,51275.0,101.20,SEC,abnormal,PTT
856000,1780,149672,2140-07-10 22:21:00,NaN,LAB,NaN,51249.0,35.90,%,abnormal,MCHC
856001,1780,149672,2140-07-10 22:21:00,NaN,LAB,NaN,51250.0,84.00,FL,normal,MCV
856002,1780,149672,2140-07-10 22:21:00,NaN,LAB,NaN,51265.0,188.00,K/UL,normal,Platelet Count
856003,1780,149672,2140-07-10 22:21:00,NaN,LAB,NaN,51277.0,16.80,%,abnormal,RDW
856004,1780,149672,2140-07-10 22:21:00,NaN,LAB,NaN,51279.0,3.14,M/UL,abnormal,Red Blood Cells
856005,1780,149672,2140-07-10 22:21:00,NaN,LAB,NaN,51301.0,9.00,K/UL,normal,White Blood Cells
856006,1780,149672,2140-07-10 22:21:00,NaN,LAB,NaN,51221.0,26.20,%,abnormal,Hematocrit
856007,1780,149672,2140-07-10 22:21:00,NaN,LAB,NaN,51222.0,9.40,G/DL,abnormal,Hemoglobin
856008,1780,149672,2140-07-10 22:21:00,NaN,LAB,NaN,51248.0,30.00,PG,normal,MCH
856009,1780,149672,2140-07-11 00:00:00,00074131230,MED,NaN,NaN,NaN,NaN,NaN,Hydromorphone
856010,1780,149672,2140-07-11 00:00:00,00469065773,MED,NaN,NaN,NaN,NaN,NaN,Tacrolimus
856011,1780,149672,2140-07-11 00:00:00,00056016975,MED,NaN,NaN,NaN,NaN,NaN,Warfarin
856012,1780,149672,2140-07-11 00:00:00,00206845216,MED,NaN,NaN,NaN,NaN,NaN,
856013,1780,149672,2140-07-11 00:00:00,00045006701,MED,NaN,NaN,NaN,NaN,NaN,
856014,1780,149672,2140-07-11 00:00:00,55513012610,MED,NaN,NaN,NaN,NaN,NaN,
856015,1780,149672,2140-07-11 00:00:00,00004003822,MED,NaN,NaN,NaN,NaN,NaN,Valganciclovir HCl
856016,1780,149672,2140-07-11 00:00:00,59676030401,MED,NaN,NaN,NaN,NaN,NaN,
856017,1780,149672,2140-07-11 00:00:00,51079090601,MED,NaN,NaN,NaN,NaN,NaN,Amiodarone HCl
856018,1780,149672,2140-07-11 01:31:00,NaN,LAB,NaN,50861.0,34.00,IU/L,normal,Alanine Aminotransferase (ALT)
856019,1780,149672,2140-07-11 01:31:00,NaN,LAB,NaN,50863.0,50.00,IU/L,normal,Alkaline Phosphatase
856020,1780,149672,2140-07-11 01:31:00,NaN,LAB,NaN,50867.0,51.00,IU/L,normal,Amylase
856021,1780,149672,2140-07-11 01:31:00,NaN,LAB,NaN,50868.0,20.00,MEQ/L,normal,Anion Gap
856022,1780,149672,2140-07-11 01:31:00,NaN,LAB,NaN,50878.0,23.00,IU/L,normal,Asparate Aminotransferase (AST)
856023,1780,149672,2140-07-11 01:31:00,NaN,LAB,NaN,50882.0,21.00,MEQ/L,abnormal,Bicarbonate
856024,1780,149672,2140-07-11 01:31:00,NaN,LAB,NaN,50885.0,0.20,MG/DL,normal,"Bilirubin, Total"
856025,1780,149672,2140-07-11 01:31:00,NaN,LAB,NaN,50893.0,8.40,MG/DL,normal,"Calcium, Total"
856026,1780,149672,2140-07-11 01:31:00,NaN,LAB,NaN,50902.0,101.00,MEQ/L,normal,Chloride
856027,1780,149672,2140-07-11 01:31:00,NaN,LAB,NaN,50912.0,3.50,MG/DL,abnormal,Creatinine
856028,1780,149672,2140-07-11 01:31:00,NaN,LAB,NaN,50924.0,1361.00,NG/ML,abnormal,Ferritin
856029,1780,149672,2140-07-11 01:31:00,NaN,LAB,NaN,50931.0,129.00,MG/DL,abnormal,Glucose
856030,1780,149672,2140-07-11 01:31:00,NaN,LAB,NaN,50952.0,28.00,UG/DL,abnormal,Iron
856031,1780,149672,2140-07-11 01:31:00,NaN,LAB,NaN,50953.0,137.00,UG/DL,abnormal,"Iron Binding Capacity, Total"
856032,1780,149672,2140-07-11 01:31:00,NaN,LAB,NaN,50956.0,41.00,IU/L,normal,Lipase

In [7]:
type_len = 5
types = list(data_df["TYPE"].unique())
type_dfs = []
for t in types:
    t_df = data_df[data_df["TYPE"] == t]
    start_id = random.randint(0, len(t_df) - type_len)
    type_dfs.append(t_df[start_id: start_id + type_len])
show_df = pd.concat(type_dfs)
show_df = show_df.apply(add_name, axis=1)

In [8]:
show_df

,SUBJECT_ID,HADM_ID,DATETIME,NDC,TYPE,ICD9_CODE,ITEMID,VALUENUM,VALUEUOM,FLAG,NAME
853439,1780,149672,2140-06-24 00:00:00,00074792201,MED,NaN,NaN,NaN,NaN,NaN,
853440,1780,149672,2140-06-24 00:00:00,00472500360,MED,NaN,NaN,NaN,NaN,NaN,Nystatin Oral Suspension
853613,1780,149672,2140-06-25 00:00:00,00338055318,MED,NaN,NaN,NaN,NaN,NaN,
853614,1780,149672,2140-06-25 00:00:00,00338004902,MED,NaN,NaN,NaN,NaN,NaN,
853615,1780,149672,2140-06-25 00:00:00,10019063002,MED,NaN,NaN,NaN,NaN,NaN,
853868,1780,149672,2140-06-26 09:23:00,NaN,LAB,NaN,51275.0,37.6,SEC,abnormal,PTT
853869,1780,149672,2140-06-26 09:23:00,NaN,LAB,NaN,51277.0,15.9,%,abnormal,RDW
853870,1780,149672,2140-06-26 09:23:00,NaN,LAB,NaN,51279.0,3.4,M/UL,abnormal,Red Blood Cells
853871,1780,149672,2140-06-26 09:23:00,NaN,LAB,NaN,51301.0,8.5,K/UL,normal,White Blood Cells
853872,1780,149672,2140-06-26 09:35:00,NaN,LAB,NaN,50802.0,-5.0,MEQ/L,normal,Base Excess
857428,1780,149672,NaT,NaN,DIAG,5570,NaN,NaN,NaN,NaN,Acute vascular insufficiency of intestine
857429,1780,149672,NaT,NaN,DIAG,99883,NaN,NaN,NaN,NaN,Non-healing surgical wound
857430,1780,149672,NaT,NaN,DIAG,48282,NaN,NaN,NaN,NaN,Pneumonia due to escherichia coli [E. coli]
857431,1780,149672,NaT,NaN,DIAG,4821,NaN,NaN,NaN,NaN,Pneumonia due to Pseudomonas
857432,1780,149672,NaT,NaN,DIAG,9982,NaN,NaN,NaN,NaN,Accidental puncture or laceration during a pro...
857449,1780,149672,NaT,NaN,PROC,0443,NaN,NaN,NaN,NaN,Release of carpal tunnel
857450,1780,149672,NaT,NaN,PROC,8209,NaN,NaN,NaN,NaN,Other incision of soft tissue of hand
857451,1780,149672,NaT,NaN,PROC,5682,NaN,NaN,NaN,NaN,Suture of laceration of ureter
857452,1780,149672,NaT,NaN,PROC,5472,NaN,NaN,NaN,NaN,Other repair of abdominal wall
857453,1780,149672,NaT,NaN,PROC,387,NaN,NaN,NaN,NaN,Interruption of the vena cava