In [1]:
import pandas as pd
import random
import os
import dill

In [2]:
data_path = "./processed_data/pretrain_lab_data.pkl"
data_df = pd.read_pickle(data_path)

In [3]:
def add_name(row):
    typ = row["TYPE"]
    if typ == "MED":
        item_id = row["NDC"]
    elif typ in ["DIAG", "PROC"]:
        item_id = row["ICD9_CODE"]
    elif typ == "LAB":
        item_id = row["ITEMID"]
    idx = vocab.get_word_id(item_id, typ)
    row["NAME"] = vocab.idx2detail[idx]
    return row

In [4]:
# data_dir = "/home/xyz/xyz/Datasets/mimiciii-1.4/"
# diag_df = pd.read_csv(os.path.join(data_dir, "D_ICD_DIAGNOSES.csv"))
# proc_df = pd.read_csv(os.path.join(data_dir, "D_ICD_PROCEDURES.csv"))
# labitem_df = pd.read_csv(os.path.join(data_dir, "D_LABITEMS.csv"))
vocab = dill.load(open("./processed_data/pretrain_lab_vocab.pkl", "rb"))

In [5]:
subject_id = data_df["SUBJECT_ID"][random.randint(0, len(data_df))]
data_df = data_df[data_df["SUBJECT_ID"] == subject_id]

In [6]:
type_len = 3
types = list(data_df["TYPE"].unique())
type_dfs = []
for t in types:
    t_df = data_df[data_df["TYPE"] == t]
    start_id = random.randint(0, len(t_df) - type_len)
    type_dfs.append(t_df[start_id: start_id + type_len])
show_df = pd.concat(type_dfs)
show_df = show_df.apply(add_name, axis=1)

In [7]:
show_df

,SUBJECT_ID,HADM_ID,DATETIME,NDC,TYPE,ICD9_CODE,ITEMID,VALUENUM,VALUEUOM,FLAG,NAME
856016,1780,149672,2140-07-11 00:00:00,59676030401,MED,NaN,NaN,NaN,NaN,NaN,
856017,1780,149672,2140-07-11 00:00:00,51079090601,MED,NaN,NaN,NaN,NaN,NaN,Amiodarone HCl
856053,1780,149672,2140-07-12 00:00:00,00469061711,MED,NaN,NaN,NaN,NaN,NaN,Tacrolimus
855788,1780,149672,2140-07-08 07:22:00,NaN,LAB,NaN,50971.0,4.6,MEQ/L,normal,Potassium
855789,1780,149672,2140-07-08 07:22:00,NaN,LAB,NaN,50983.0,135.0,MEQ/L,normal,Sodium
855790,1780,149672,2140-07-08 07:22:00,NaN,LAB,NaN,51006.0,54.0,MG/DL,abnormal,Urea Nitrogen
857422,1780,149672,NaT,NaN,DIAG,99681,NaN,NaN,NaN,NaN,Complications of transplanted kidney
857423,1780,149672,NaT,NaN,DIAG,9972,NaN,NaN,NaN,NaN,"Peripheral vascular complications, not elsewhe..."
857424,1780,149672,NaT,NaN,DIAG,72888,NaN,NaN,NaN,NaN,Rhabdomyolysis
857446,1780,149672,NaT,NaN,PROC,4601,NaN,NaN,NaN,NaN,Exteriorization of small intestine
857447,1780,149672,NaT,NaN,PROC,3809,NaN,NaN,NaN,NaN,"Incision of vessel, lower limb veins"
857448,1780,149672,NaT,NaN,PROC,4591,NaN,NaN,NaN,NaN,Small-to-small intestinal anastomosis